### ISSUE TITLE
Unknown variable reference in PDF theme

### ISSUE THREAD

**Issue by ashleyha** [opengeospatial/er_template#12]
I am using the er_template for the GPKG-RTE engineering report. When compiling the raw files for PDF output using this command:

```asciidoctor-pdf -a pdf-stylesdir=resources -a pdf-style=ogc -a pdf-fontsdir=resources/fonts er.adoc```

I got this warning:

```WARNING: unknown variable reference in PDF theme: $header_recto_center_content```

I was able to get rid of the warning by commenting out the last line in ogc-theme.yml, however I wasn't sure if there is another preferred solution.

**Comment by ingosimonis** [comment]
@ashleyholt please, which version of asciidoctor did you use? I cannot reproduce that error

**Comment by hylkevds** [comment]
I just noticed it as well, using the docker image of asciidoctor.

**Comment by hylkevds** [comment]
I'm experimenting with a travis build for our SensorThings documents:
Source: https://github.com/hylkevds/sensorthings/tree/18-056
Build with the error: https://travis-ci.org/hylkevds/sensorthings/builds/436031818
PDF with the missing footer: https://hylkevds.github.io/sensorthings/18-056/18-056/18-056.pdf

**Comment by ingosimonis** [comment]
Interesting. I just compiled @hylkevds SensorThings documents using 
Asciidoctor PDF 1.5.0.alpha.15 using Asciidoctor 1.5.5 [http://asciidoctor.org]
Runtime Environment (ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]) (lc:UTF-8 fs:UTF-8 in:- ex:UTF-8)
and it compiles without any issues: 
[OGC_18-056.pdf](https://github.com/opengeospatial/er_template/files/2437285/OGC_18-056.pdf)

**Comment by ingosimonis** [comment]
In any case, I will comment out the last line in the yml-style file. It was left there unintentionally anyway

**Comment by hylkevds** [comment]
For reference, the current docker image uses:
Asciidoctor PDF 1.5.0.alpha.16 using Asciidoctor 1.5.7.1 [https://asciidoctor.org]
Runtime Environment (ruby 2.4.4p296 (2018-03-28 revision 63013) [x86_64-linux-musl]) (lc:UTF-8 fs:UTF-8 in:UTF-8 ex:UTF-8)

**Comment by ingosimonis** [comment]
I updated 
[https://github.com/opengeospatial/er_template/blob/master/resources/ogc-theme.yml](https://github.com/opengeospatial/er_template/blob/master/resources/ogc-theme.yml)

please double check if it works now without any errors

**Comment by hylkevds** [comment]
Yep, seems to work fine now:
https://hylkevds.github.io/sensorthings/18-056/18-056/18-056.pdf

**Comment by ingosimonis** [comment]
great!
