### ISSUE TITLE
PDF Generation produces extraneous blank pages

### ISSUE THREAD

**Issue by jyutzler** [opengeospatial/er_template#2]
When using a document based on this template to generate a PDF file, the PDF is generated fine through AsciiDocFX but the file has blank pages after each section.

**Comment by bpross-52n** [comment]
Possible workaround (PDFs still don't look exactly like the HTML preview, but there seem to be no more extra pages and missing elements):
- Download and extract https://github.com/asciidoctor/asciidoctor-fopub/archive/master.zip
- Export your ER as docbook using AsciidocFX
- Adjust the paths in the following command an execute it using the command line: 
  - C:\Software\asciidoctor-fopub-master\fopub.bat "C:\Testbed-12\ER.xml"

This should create C:\Testbed-12\ER.pdf

**Comment by gbuehler** [comment]
I can confirm that I was able to do this as well on a Mac.

Thanks @bpross-52n
