### ISSUE TITLE
Adding Appendix sub-sections

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/er_template#23]
While reviewing the Testbed-14 D029 ER, I stumbled across a better way to add appendix sub-sections. Instead of manually adding the sub-section numbers in the Appendix, simply add the headers the normal way but skip level 2 (==) headers. For example, 
```
[appendix]
[[ConceptualModelExpressions]]
= Conceptual Model Expressions

=== Expressions

==== Overview
Some text...
```
This approach correctly numbers the sub-sections in the Appendix. For example, A.1, A.2, A.3 etc
See an example of the resulting Table of Contents below. Note that the headers are automatically numbered.
<img width="749" alt="screenshot 2018-11-17 at 11 18 49" src="https://user-images.githubusercontent.com/18121038/48660519-c5b91f00-ea5a-11e8-8c68-efd85d897013.png">

**Comment by serich** [comment]
Thanks @ghobona . I'd have no objection to this change to the template. Anybody else want to register an objection? If not, Gobe, could you go ahead and commit the changes and create a pull request? Thanks.

**Comment by ghobona** [comment]
I do not have ‘write’ privileges on the repo so I am unable to commit any changes to it.

**Comment by serich** [comment]
@ghobona OK. Just so I'm clear, it appears that the needed fix is to replace all source-file instances of headings that start with two equals signs "== " with three equals signs "=== ", and then replace all instances of three with four, etc. Am I understanding it correctly?

@bermud @ingosimonis @gbuehler would you have any objection to my making this change to the template?

**Comment by ghobona** [comment]
No, that’s not what I meant. I will create a Pull Request after the current PR’s have been accepted and/or closed.

**Comment by ghobona** [comment]
@serich

Please see [Pull Request 25](https://github.com/opengeospatial/er_template/pull/25)
