### ISSUE TITLE
Rendering the Terms and Definitions

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/er_template#27]
The current approach for presenting the Terms and Definitions does not work well because the Asciidoc renderer does not detect the markup in definitions.

A better way to do it would be to use the approach proposed by @cportele

See the example below.

[3-terms.txt](https://github.com/opengeospatial/er_template/files/2936466/3-terms.txt)

**Comment by serich** [comment]
No objection from me.

**Comment by ghobona** [comment]
I found another way to do this. The advantage of this approach is that it maintains the use of bullets/dots, while also rendering markup.

See the example below.

[3-terms-b.txt](https://github.com/opengeospatial/er_template/files/2944792/3-terms-b.txt)

**Comment by serich** [comment]
+1

**Comment by serich** [comment]
@ghobona  I'm about to populate the Testbed-15 ER repos, so let me know if you want me to wait until you've had a chance to merge this change. Thanks.

**Comment by ghobona** [comment]
@serich 

This is addressed by Pull Request 30. Please merge the changes into the master branch.

https://github.com/opengeospatial/er_template/pull/30
