### ISSUE TITLE
Add third column to the Contacts/Contributors table to identify role

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/er_template#28]
Some of the editors are already appending (editor) to their names in the section titled "Document contributor contact points".

To ensure consistency we should introduce a third column where editors can be identified as such.

The column could be labelled 'Role', with only two values allowed: Editor, Contributor.

**Comment by serich** [comment]
No objection from me.

**Comment by serich** [comment]
@ghobona  I'm about to populate the Testbed-15 ER repos, so let me know if you want me to wait until you've had a chance to merge this change. Thanks.

**Comment by ghobona** [comment]
@serich 

This issue is addressed by Pull Request 29. Please merge the changes into the master branch.

https://github.com/opengeospatial/er_template/pull/29
